# Generated by Django 4.2.3 on 2023-08-17 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_remove_choice_poll_remove_vote_poll_delete_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Posts.post'),
        ),
        migrations.AddField(
            model_name='vote',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Posts.post'),
        ),
    ]
