# Generated by Django 4.2.3 on 2023-08-17 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_like_is_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='is_liked',
        ),
    ]
